fix: TypeError: unhashable type: 'dict'
Line that error occurred: 372
Source code that error occurred: 
```python
if v in TYPE_MAP.keys():
```
Description:
If the type of "v" is "dict" or "list", it will raise an exception like below.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/lambda_local/main.py", line 92, in execute
    result = func(event, context.activate())
  File "app.py", line 141, in handler
    wsdl = dispatcher.wsdl()
  File "/rempus/soap_transition/pysimplesoap/server.py", line 391, in wsdl
    parse_element("%s" % method, args and args.items())
  File "/rempus/soap_transition/pysimplesoap/server.py", line 372, in parse_element
    if v in TYPE_MAP.keys():
TypeError: unhashable type: 'dict'

So, I've changed the order of if, elif lines and logic belong them. Let it check by isinstance method first, then check if it is None, and finally the rest checking logic go through.